// SPDX-FileCopyrightText: Copyright 2026 Citron Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#version 450

layout(local_size_x = 1) in;

layout(std430, binding = 0) buffer Indirect {
    uint x;
    uint y;
    uint z;
};

layout(push_constant) uniform PushConstants {
    uint max_dim;
};

void main() {
    x = min(x, max_dim);
    y = min(y, max_dim);
    z = min(z, max_dim);
}
